apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: tcp-ilb
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: web
  type: LoadBalancer
